---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: installer
  name: installer
spec:
  image:
    name: calunga-tenant/installer

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: installer
spec:
  componentName: installer
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/installer
