---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: poetry-core
  name: poetry-core
spec:
  image:
    name: calunga-tenant/poetry-core

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: poetry-core
spec:
  componentName: poetry-core
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/poetry-core
