---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: isodate
  name: isodate
spec:
  image:
    name: calunga-tenant/isodate

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: isodate
spec:
  componentName: isodate
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/isodate
