---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: humanfriendly
  name: humanfriendly
spec:
  image:
    name: calunga-tenant/humanfriendly

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: humanfriendly
spec:
  componentName: humanfriendly
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/humanfriendly
