---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: asttokens
  name: asttokens
spec:
  image:
    name: calunga-tenant/asttokens

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: asttokens
spec:
  componentName: asttokens
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/asttokens
