---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: requests-aws4auth
  name: requests-aws4auth
spec:
  image:
    name: calunga-tenant/requests-aws4auth

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: requests-aws4auth
spec:
  componentName: requests-aws4auth
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/requests-aws4auth
