---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: crashtest
  name: crashtest
spec:
  image:
    name: calunga-tenant/crashtest

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: crashtest
spec:
  componentName: crashtest
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/crashtest
