---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: argcomplete
  name: argcomplete
spec:
  image:
    name: calunga-tenant/argcomplete

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: argcomplete
spec:
  componentName: argcomplete
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/argcomplete
