---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: multiprocess
  name: multiprocess
spec:
  image:
    name: calunga-tenant/multiprocess

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: multiprocess
spec:
  componentName: multiprocess
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/multiprocess
