---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jupyter-core
  name: jupyter-core
spec:
  image:
    name: calunga-tenant/jupyter-core

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jupyter-core
spec:
  componentName: jupyter-core
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jupyter-core
