---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: sympy
  name: sympy
spec:
  image:
    name: calunga-tenant/sympy

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: sympy
spec:
  componentName: sympy
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/sympy
