---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: flake8
  name: flake8
spec:
  image:
    name: calunga-tenant/flake8

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: flake8
spec:
  componentName: flake8
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/flake8
