---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: executing
  name: executing
spec:
  image:
    name: calunga-tenant/executing

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: executing
spec:
  componentName: executing
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/executing
