---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: typer
  name: typer
spec:
  image:
    name: calunga-tenant/typer

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: typer
spec:
  componentName: typer
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/typer
