---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: datadog
  name: datadog
spec:
  image:
    name: calunga-tenant/datadog

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: datadog
spec:
  componentName: datadog
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/datadog
