---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: simplejson
  name: simplejson
spec:
  image:
    name: calunga-tenant/simplejson

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: simplejson
spec:
  componentName: simplejson
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/simplejson
