---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: cattrs
  name: cattrs
spec:
  image:
    name: calunga-tenant/cattrs

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: cattrs
spec:
  componentName: cattrs
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/cattrs
