---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pycryptodomex
  name: pycryptodomex
spec:
  image:
    name: calunga-tenant/pycryptodomex

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pycryptodomex
spec:
  componentName: pycryptodomex
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pycryptodomex
