---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: execnet
  name: execnet
spec:
  image:
    name: calunga-tenant/execnet

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: execnet
spec:
  componentName: execnet
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/execnet
