---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: nltk
  name: nltk
spec:
  image:
    name: calunga-tenant/nltk

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: nltk
spec:
  componentName: nltk
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/nltk
