---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: overrides
  name: overrides
spec:
  image:
    name: calunga-tenant/overrides

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: overrides
spec:
  componentName: overrides
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/overrides
