---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: websocket-client
  name: websocket-client
spec:
  image:
    name: calunga-tenant/websocket-client

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: websocket-client
spec:
  componentName: websocket-client
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/websocket-client
