---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: werkzeug
  name: werkzeug
spec:
  image:
    name: calunga-tenant/werkzeug

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: werkzeug
spec:
  componentName: werkzeug
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/werkzeug
