---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jedi
  name: jedi
spec:
  image:
    name: calunga-tenant/jedi

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jedi
spec:
  componentName: jedi
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jedi
