---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: joblib
  name: joblib
spec:
  image:
    name: calunga-tenant/joblib

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: joblib
spec:
  componentName: joblib
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/joblib
