---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: prometheus-client
  name: prometheus-client
spec:
  image:
    name: calunga-tenant/prometheus-client

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: prometheus-client
spec:
  componentName: prometheus-client
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/prometheus-client
