---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pyopenssl
  name: pyopenssl
spec:
  image:
    name: calunga-tenant/pyopenssl

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pyopenssl
spec:
  componentName: pyopenssl
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pyopenssl
