---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pyrsistent
  name: pyrsistent
spec:
  image:
    name: calunga-tenant/pyrsistent

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pyrsistent
spec:
  componentName: pyrsistent
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pyrsistent
