---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: gcsfs
  name: gcsfs
spec:
  image:
    name: calunga-tenant/gcsfs

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: gcsfs
spec:
  componentName: gcsfs
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/gcsfs
