---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: sqlalchemy-spanner
  name: sqlalchemy-spanner
spec:
  image:
    name: calunga-tenant/sqlalchemy-spanner

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: sqlalchemy-spanner
spec:
  componentName: sqlalchemy-spanner
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/sqlalchemy-spanner
