---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: aws-lambda-powertools
  name: aws-lambda-powertools
spec:
  image:
    name: calunga-tenant/aws-lambda-powertools

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: aws-lambda-powertools
spec:
  componentName: aws-lambda-powertools
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/aws-lambda-powertools
