---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jaraco-context
  name: jaraco-context
spec:
  image:
    name: calunga-tenant/jaraco-context

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jaraco-context
spec:
  componentName: jaraco-context
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jaraco-context
