---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pymysql
  name: pymysql
spec:
  image:
    name: calunga-tenant/pymysql

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pymysql
spec:
  componentName: pymysql
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pymysql
