---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: identify
  name: identify
spec:
  image:
    name: calunga-tenant/identify

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: identify
spec:
  componentName: identify
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/identify
