---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: terminado
  name: terminado
spec:
  image:
    name: calunga-tenant/terminado

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: terminado
spec:
  componentName: terminado
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/terminado
