---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pytest-asyncio
  name: pytest-asyncio
spec:
  image:
    name: calunga-tenant/pytest-asyncio

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pytest-asyncio
spec:
  componentName: pytest-asyncio
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pytest-asyncio
