---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: databricks-sdk
  name: databricks-sdk
spec:
  image:
    name: calunga-tenant/databricks-sdk

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: databricks-sdk
spec:
  componentName: databricks-sdk
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/databricks-sdk
