---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: python-json-logger
  name: python-json-logger
spec:
  image:
    name: calunga-tenant/python-json-logger

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: python-json-logger
spec:
  componentName: python-json-logger
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/python-json-logger
