---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: graphql-core
  name: graphql-core
spec:
  image:
    name: calunga-tenant/graphql-core

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: graphql-core
spec:
  componentName: graphql-core
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/graphql-core
