---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: lazy-object-proxy
  name: lazy-object-proxy
spec:
  image:
    name: calunga-tenant/lazy-object-proxy

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: lazy-object-proxy
spec:
  componentName: lazy-object-proxy
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/lazy-object-proxy
