---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pyflakes
  name: pyflakes
spec:
  image:
    name: calunga-tenant/pyflakes

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pyflakes
spec:
  componentName: pyflakes
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pyflakes
