---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: websockets
  name: websockets
spec:
  image:
    name: calunga-tenant/websockets

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: websockets
spec:
  componentName: websockets
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/websockets
