---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: hvac
  name: hvac
spec:
  image:
    name: calunga-tenant/hvac

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hvac
spec:
  componentName: hvac
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/hvac
