---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: hpack
  name: hpack
spec:
  image:
    name: calunga-tenant/hpack

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hpack
spec:
  componentName: hpack
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/hpack
