---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: azure-keyvault-secrets
  name: azure-keyvault-secrets
spec:
  image:
    name: calunga-tenant/azure-keyvault-secrets

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: azure-keyvault-secrets
spec:
  componentName: azure-keyvault-secrets
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/azure-keyvault-secrets
