---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: zipp
  name: zipp
spec:
  image:
    name: calunga-tenant/zipp

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: zipp
spec:
  componentName: zipp
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/zipp
