---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: semver
  name: semver
spec:
  image:
    name: calunga-tenant/semver

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: semver
spec:
  componentName: semver
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/semver
