---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: dulwich
  name: dulwich
spec:
  image:
    name: calunga-tenant/dulwich

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: dulwich
spec:
  componentName: dulwich
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/dulwich
