---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: uvicorn
  name: uvicorn
spec:
  image:
    name: calunga-tenant/uvicorn

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: uvicorn
spec:
  componentName: uvicorn
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/uvicorn
