---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pytest-mock
  name: pytest-mock
spec:
  image:
    name: calunga-tenant/pytest-mock

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pytest-mock
spec:
  componentName: pytest-mock
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pytest-mock
