---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jsonpointer
  name: jsonpointer
spec:
  image:
    name: calunga-tenant/jsonpointer

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jsonpointer
spec:
  componentName: jsonpointer
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jsonpointer
