---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: uvloop
  name: uvloop
spec:
  image:
    name: calunga-tenant/uvloop

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: uvloop
spec:
  componentName: uvloop
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/uvloop
