---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: sqlalchemy-bigquery
  name: sqlalchemy-bigquery
spec:
  image:
    name: calunga-tenant/sqlalchemy-bigquery

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: sqlalchemy-bigquery
spec:
  componentName: sqlalchemy-bigquery
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/sqlalchemy-bigquery
