---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pip
  name: pip
spec:
  image:
    name: calunga-tenant/pip

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pip
spec:
  componentName: pip
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pip
