---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: httptools
  name: httptools
spec:
  image:
    name: calunga-tenant/httptools

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: httptools
spec:
  componentName: httptools
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/httptools
