---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: psutil
  name: psutil
spec:
  image:
    name: calunga-tenant/psutil

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: psutil
spec:
  componentName: psutil
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/psutil
