---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pinotdb
  name: pinotdb
spec:
  image:
    name: calunga-tenant/pinotdb

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pinotdb
spec:
  componentName: pinotdb
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pinotdb
