---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: mistune
  name: mistune
spec:
  image:
    name: calunga-tenant/mistune

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: mistune
spec:
  componentName: mistune
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/mistune
