---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: tenacity
  name: tenacity
spec:
  image:
    name: calunga-tenant/tenacity

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: tenacity
spec:
  componentName: tenacity
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/tenacity
