---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jsonpatch
  name: jsonpatch
spec:
  image:
    name: calunga-tenant/jsonpatch

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jsonpatch
spec:
  componentName: jsonpatch
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jsonpatch
