---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: babel
  name: babel
spec:
  image:
    name: calunga-tenant/babel

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: babel
spec:
  componentName: babel
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/babel
