---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: requests-file
  name: requests-file
spec:
  image:
    name: calunga-tenant/requests-file

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: requests-file
spec:
  componentName: requests-file
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/requests-file
