---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: toolz
  name: toolz
spec:
  image:
    name: calunga-tenant/toolz

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: toolz
spec:
  componentName: toolz
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/toolz
