---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: gitdb
  name: gitdb
spec:
  image:
    name: calunga-tenant/gitdb

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: gitdb
spec:
  componentName: gitdb
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/gitdb
