---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: stack-data
  name: stack-data
spec:
  image:
    name: calunga-tenant/stack-data

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: stack-data
spec:
  componentName: stack-data
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/stack-data
