---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: distro
  name: distro
spec:
  image:
    name: calunga-tenant/distro

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: distro
spec:
  componentName: distro
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/distro
