---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: cloudpickle
  name: cloudpickle
spec:
  image:
    name: calunga-tenant/cloudpickle

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: cloudpickle
spec:
  componentName: cloudpickle
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/cloudpickle
