---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: yamllint
  name: yamllint
spec:
  image:
    name: calunga-tenant/yamllint

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: yamllint
spec:
  componentName: yamllint
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/yamllint
