---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: schema
  name: schema
spec:
  image:
    name: calunga-tenant/schema

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: schema
spec:
  componentName: schema
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/schema
