---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: croniter
  name: croniter
spec:
  image:
    name: calunga-tenant/croniter

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: croniter
spec:
  componentName: croniter
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/croniter
