---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jupyter-client
  name: jupyter-client
spec:
  image:
    name: calunga-tenant/jupyter-client

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jupyter-client
spec:
  componentName: jupyter-client
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jupyter-client
