---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: awswrangler
  name: awswrangler
spec:
  image:
    name: calunga-tenant/awswrangler

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: awswrangler
spec:
  componentName: awswrangler
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/awswrangler
