---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: fastjsonschema
  name: fastjsonschema
spec:
  image:
    name: calunga-tenant/fastjsonschema

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: fastjsonschema
spec:
  componentName: fastjsonschema
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/fastjsonschema
