---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: multidict
  name: multidict
spec:
  image:
    name: calunga-tenant/multidict

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: multidict
spec:
  componentName: multidict
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/multidict
