---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: debugpy
  name: debugpy
spec:
  image:
    name: calunga-tenant/debugpy

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: debugpy
spec:
  componentName: debugpy
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/debugpy
