---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: delta-spark
  name: delta-spark
spec:
  image:
    name: calunga-tenant/delta-spark

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: delta-spark
spec:
  componentName: delta-spark
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/delta-spark
