---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: astroid
  name: astroid
spec:
  image:
    name: calunga-tenant/astroid

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: astroid
spec:
  componentName: astroid
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/astroid
