---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pyproject-hooks
  name: pyproject-hooks
spec:
  image:
    name: calunga-tenant/pyproject-hooks

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pyproject-hooks
spec:
  componentName: pyproject-hooks
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pyproject-hooks
