---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: exceptiongroup
  name: exceptiongroup
spec:
  image:
    name: calunga-tenant/exceptiongroup

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: exceptiongroup
spec:
  componentName: exceptiongroup
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/exceptiongroup
