---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pkginfo
  name: pkginfo
spec:
  image:
    name: calunga-tenant/pkginfo

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pkginfo
spec:
  componentName: pkginfo
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pkginfo
