---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pexpect
  name: pexpect
spec:
  image:
    name: calunga-tenant/pexpect

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pexpect
spec:
  componentName: pexpect
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pexpect
