---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: azure-core
  name: azure-core
spec:
  image:
    name: calunga-tenant/azure-core

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: azure-core
spec:
  componentName: azure-core
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/azure-core
