---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pylint
  name: pylint
spec:
  image:
    name: calunga-tenant/pylint

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pylint
spec:
  componentName: pylint
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pylint
