---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: nodeenv
  name: nodeenv
spec:
  image:
    name: calunga-tenant/nodeenv

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: nodeenv
spec:
  componentName: nodeenv
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/nodeenv
