---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: mpmath
  name: mpmath
spec:
  image:
    name: calunga-tenant/mpmath

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: mpmath
spec:
  componentName: mpmath
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/mpmath
