---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pytest-cov
  name: pytest-cov
spec:
  image:
    name: calunga-tenant/pytest-cov

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pytest-cov
spec:
  componentName: pytest-cov
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pytest-cov
