---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: threadpoolctl
  name: threadpoolctl
spec:
  image:
    name: calunga-tenant/threadpoolctl

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: threadpoolctl
spec:
  componentName: threadpoolctl
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/threadpoolctl
