---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: langchain
  name: langchain
spec:
  image:
    name: calunga-tenant/langchain

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: langchain
spec:
  componentName: langchain
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/langchain
