---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: docker
  name: docker
spec:
  image:
    name: calunga-tenant/docker

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: docker
spec:
  componentName: docker
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/docker
