---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: portalocker
  name: portalocker
spec:
  image:
    name: calunga-tenant/portalocker

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: portalocker
spec:
  componentName: portalocker
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/portalocker
