---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: jeepney
  name: jeepney
spec:
  image:
    name: calunga-tenant/jeepney

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: jeepney
spec:
  componentName: jeepney
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/jeepney
