---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: docstring-parser
  name: docstring-parser
spec:
  image:
    name: calunga-tenant/docstring-parser

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: docstring-parser
spec:
  componentName: docstring-parser
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/docstring-parser
