---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: webencodings
  name: webencodings
spec:
  image:
    name: calunga-tenant/webencodings

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: webencodings
spec:
  componentName: webencodings
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/webencodings
