---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: backoff
  name: backoff
spec:
  image:
    name: calunga-tenant/backoff

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: backoff
spec:
  componentName: backoff
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/backoff
