---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: starlette
  name: starlette
spec:
  image:
    name: calunga-tenant/starlette

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: starlette
spec:
  componentName: starlette
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/starlette
