---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pyspark
  name: pyspark
spec:
  image:
    name: calunga-tenant/pyspark

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pyspark
spec:
  componentName: pyspark
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pyspark
