---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pandas-gbq
  name: pandas-gbq
spec:
  image:
    name: calunga-tenant/pandas-gbq

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pandas-gbq
spec:
  componentName: pandas-gbq
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pandas-gbq
