---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: smmap
  name: smmap
spec:
  image:
    name: calunga-tenant/smmap

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: smmap
spec:
  componentName: smmap
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/smmap
