---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: pygithub
  name: pygithub
spec:
  image:
    name: calunga-tenant/pygithub

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: pygithub
spec:
  componentName: pygithub
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/pygithub
