---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: poetry-plugin-export
  name: poetry-plugin-export
spec:
  image:
    name: calunga-tenant/poetry-plugin-export

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: poetry-plugin-export
spec:
  componentName: poetry-plugin-export
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/poetry-plugin-export
