---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: inflection
  name: inflection
spec:
  image:
    name: calunga-tenant/inflection

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: inflection
spec:
  componentName: inflection
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/inflection
