---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: mccabe
  name: mccabe
spec:
  image:
    name: calunga-tenant/mccabe

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: mccabe
spec:
  componentName: mccabe
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/mccabe
