---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: sqlalchemy
  name: sqlalchemy
spec:
  image:
    name: calunga-tenant/sqlalchemy

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: sqlalchemy
spec:
  componentName: sqlalchemy
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/sqlalchemy
