---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: itsdangerous
  name: itsdangerous
spec:
  image:
    name: calunga-tenant/itsdangerous

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: itsdangerous
spec:
  componentName: itsdangerous
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/itsdangerous
