---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: cfgv
  name: cfgv
spec:
  image:
    name: calunga-tenant/cfgv

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: cfgv
spec:
  componentName: cfgv
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/cfgv
