---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: ImageRepository
      name: .*
    path: set-resource-name.yaml

  - target:
      kind: Component
      name: .*
    path: set-resource-name.yaml

  - path: set-package-name.yaml
