---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: gunicorn
  name: gunicorn
spec:
  image:
    name: calunga-tenant/gunicorn

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: gunicorn
spec:
  componentName: gunicorn
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/gunicorn
