---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: lxml
  name: lxml
spec:
  image:
    name: calunga-tenant/lxml

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: lxml
spec:
  componentName: lxml
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/lxml
