---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: adal
  name: adal
spec:
  image:
    name: calunga-tenant/adal

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: adal
spec:
  componentName: adal
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/adal
