---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: opentelemetry-instrumentation-requests
  name: opentelemetry-instrumentation-requests
spec:
  image:
    name: calunga-tenant/opentelemetry-instrumentation-requests

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: opentelemetry-instrumentation-requests
spec:
  componentName: opentelemetry-instrumentation-requests
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/opentelemetry-instrumentation-requests
