---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/component: parso
  name: parso
spec:
  image:
    name: calunga-tenant/parso

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: parso
spec:
  componentName: parso
  containerImage: quay.io/redhat-user-workloads/calunga-tenant/parso
